server/demo/chat/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

server/demo/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from django.contrib import admin
from django.urls import include, path

from hide.views import base_views
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('hide/', include('hide.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path

    path('chat/', include('chat.urls')),


    # 인증 관련
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

handler404 = 'common.views.page_not_found'

server/demo/hide/urls.py
from django.urls import path

from .views import base_views, myfile_views
from .views import rest_pc_views, rest_mobile_views, rest_network_state_views

app_name = 'hide'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('myfile/', base_views.myfile_list, name='myfile_list'),

    # myfile_views.py
    path('myfile/create/', myfile_views.myfile_create, name='myfile_create'),
    path('myfile/modify/<int:current_author_id>/<int:myfile_id>/', myfile_views.myfile_modify, name='myfile_modify'),
    path('myfile/delete/<int:current_author_id>/', myfile_views.myfile_delete, name='myfile_delete'),

    # rest_pc_views.py
    path('myfile/rest/create/', rest_pc_views.rest_myfile_create, name='rest_myfile_create'),
    path('myfile/rest/delete/', rest_pc_views.rest_myfile_delete, name='rest_myfile_delete'),

    # rest_mobile_views.py
    path('myfile/rest/get_list/', rest_mobile_views.rest_get_myfile_list, name='rest_get_myfile_list'),

    # rest_network_state_views.py
    path('myfile/rest/get_network_state/', rest_network_state_views.rest_get_network_state, name='rest_get_network_state'),
]

server/demo/hide/models.py
from django.db import models
from django.contrib.auth.models import User

class Myfile(models.Model):
    class Meta:
        unique_together = (('author', 'file_path'))
    file_path = models.CharField(db_column="FILE_PATH", max_length=200)
    state = models.BooleanField(db_column="STATE")
    author = models.ForeignKey(User, on_delete=models.CASCADE)


class NetworkState(models.Model):
    network_state = models.BooleanField(db_column="NETWORK_STATE", default="False")
    author = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

server/demo/hide/forms.py
from django import forms
from .models import Myfile, NetworkState

class MyfileForm(forms.ModelForm):
    class Meta:
        model = Myfile
        fields = ['file_path', 'state']
        labels = {
            'file_path': 'file_path',
            'state': 'state',
        }

class NetworkStateForm(forms.ModelForm):
    from rest_framework.permissions import IsAuthenticated
    permission_classes = (IsAuthenticated,)

    class Meta:
        model = NetworkState
        fields = ['network_state']
        labels = {
            'network_state': 'network_state',
        }

server/demo/hide/views/base_views.py
import logging

from django.core.paginator import Paginator
from django.shortcuts import render

from ..models import Myfile, NetworkState

logger = logging.getLogger('hide')

def index(request):
    return render(request, 'hide/home.html')


def myfile_list(request):
    page = request.GET.get('page', '1')  # 페이지

    myfile_list = Myfile.objects.order_by('-id')
    network_state_list = NetworkState.objects.filter(author_id=request.user.id)

    # 페이징처리
    paginator = Paginator(myfile_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'myfile_list': page_obj, 'network_state_list': network_state_list,
               'page': page}

    return render(request, 'hide/myfile_list.html', context)

server/demo/hide/views/myfile_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import MyfileForm, NetworkStateForm
from ..models import Myfile, NetworkState


@login_required(login_url='common:login')
def myfile_create(request):
    if request.method == 'POST':
        form = MyfileForm(request.POST)
        if form.is_valid():
            myfile = form.save(commit=False)
            myfile.author = request.user  # 추가한 속성 author 적용

            # (author, index) already exist
            if myfile.validate_unique():
                messages.error(request, '추가할 수 없습니다')
                # return redirect('hide:index')
            # create success
            else:
                myfile.save()
                return redirect('hide:myfile_list')

            # return redirect('hide:index')
    else:
        form = MyfileForm()
    context = {'form': form}
    return render(request, 'hide/myfile_form.html', context)


@login_required(login_url='common:login')
def myfile_modify(request, current_author_id, myfile_id):
    myfile = get_object_or_404(Myfile, id=myfile_id)

    if request.user != myfile.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('hide:index')

    if request.method == "POST":
        form = MyfileForm(request.POST, instance=myfile)
        if form.is_valid():
            myfile = form.save(commit=False)
            myfile.author = request.user

            # (author, index) already exist
            if myfile.validate_unique():
                messages.error(request, '수정할 수 없습니다')
                # return redirect('hide:index')
            # create success
            else:
                myfile.save()
                return redirect('hide:myfile_list')
    else:
        form = MyfileForm(instance=myfile)
    context = {'form': form}
    return render(request, 'hide/myfile_form.html', context)


@login_required(login_url='common:login')
def myfile_delete(request, current_author_id):
    Myfile.objects.filter(author_id=current_author_id).delete()
    return redirect('hide:myfile_list')


def network_state_check(current_user):
    my_network_state = NetworkState.objects.filter(author=current_user)
    if len(my_network_state)==0:
        network_state_modify(current_user, "False")
    return list(NetworkState.objects.filter(author=current_user))[0].network_state


def network_state_modify(current_user, state):
    form = NetworkStateForm()
    ns = form.save(commit=False)
    ns.author = current_user
    ns.network_state = state
    ns.save()

server/demo/hide/views/rest_mobile_views.py
from django.contrib.auth.decorators import login_required

from ..models import Myfile
from ..forms import MyfileForm
from . import myfile_views

from django.http import JsonResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

@login_required(login_url='rest_login')
def rest_get_myfile_list(request):
    myfiles = list(Myfile.objects.filter(author_id=request.user.id).values())
    new_dict = {'result': 'success'}
    new_dict['my_file_list']= myfiles

    if request.method == "POST":
        return JsonResponse(new_dict,
                            json_dumps_params={'ensure_ascii': True})
    else:
        return JsonResponse({'result': 'fail', 'message': 'use POST'},
                            rjson_dumps_params={'ensure_ascii': True})

server/demo/hide/views/rest_network_state_views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .myfile_views import network_state_check

@login_required(login_url='rest_login')
def rest_get_network_state(request):
    my_network_state = network_state_check(request.user)
    print('my_network_state: ' + str(my_network_state))
    new_dict = {'result': 'success', 'network_state': my_network_state}

    if request.method == "POST":
        return JsonResponse(new_dict,
                            json_dumps_params={'ensure_ascii': True})
    else:
        return JsonResponse({'result': 'fail', 'message': 'use POST'}, json_dumps_params={'ensure_ascii': True})

server/demo/hide/views/rest_pc_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from ..forms import MyfileForm
from ..models import Myfile

from django.http import JsonResponse

@login_required(login_url='rest_login')
def rest_myfile_create(request):
    if request.method == 'POST':
        form = MyfileForm(request.POST)
        if form.is_valid():
            myfile = form.save(commit=False)
            myfile.author = request.user  # 추가한 속성 author 적용

            # (author, index) already exist
            if myfile.validate_unique():
                messages.error(request, '추가할 수 없습니다')
                # return redirect('hide:index')
            # create success
            else:
                myfile.save()
                return JsonResponse({'result':'success', 'message': 'create success'},
                                    json_dumps_params = {'ensure_ascii': True})
        else:
            return JsonResponse({'result':'fail', 'message': 'form is not valid'},
                                json_dumps_params={'ensure_ascii': True})
    else:
        return JsonResponse({'result': 'fail', 'message': 'use POST'},
                            json_dumps_params = {'ensure_ascii': True})


@login_required(login_url='rest_login')
def rest_myfile_delete(request):
    if request.method == 'POST':
        Myfile.objects.filter(author_id=request.user.id).delete()
        return JsonResponse({'result': 'success', 'message': 'delete success'},
                                json_dumps_params={'ensure_ascii': True})
    else:
        return JsonResponse({'result':'fail', 'message': 'use POST'},
                            json_dumps_params={'ensure_ascii': True})


server/demo/templates/hide/myfile_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">파일 등록</h5>
    <form method="post" class="post-form my-3">
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <label for="file_path">file path</label>
            <input type="text" class="form-control" name="file_path" id="file_path"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>

        <div class="form-group">
            <label for="state">on/off state</label>
            <input type="checkbox" class="form-control" name="state" id="state"
                   value="n">
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

server/demo/templates/hide/myfile_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <div>
        Network state:
        {% if network_state_list %}
            {% for ns in network_state_list %}
            {% if request.user.id == ns.author_id %}
                {{ ns.network_state}}
            {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th style="width:50%">file path</th>
            <th>state</th>
            <th>author</th>
            <th>modify</th>
        </tr>
        </thead>
        <tbody>
        {% if myfile_list %}
        {% for myfile in myfile_list %}
        {% if request.user == myfile.author %}
        <tr class="text-center">
            <td class="text-left">
                {{ myfile.file_path }}
            </td>
            <td class="text-left">
                {% if myfile.state == True %}
                on
                {% else %}
                off
                {% endif %}
            </td>  <!-- author 추가 -->
            <td class="text-left">{{ myfile.author.username }}</td>  <!-- author 추가 -->
            <td class="text-left">
                <a href="{% url 'hide:myfile_modify' myfile.author.id myfile.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 파일이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if myfile_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ myfile_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in myfile_list.paginator.page_range %}
        {% if page_number >= myfile_list.number|add:-5 and page_number <= myfile_list.number|add:5 %}
            {% if page_number == myfile_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if myfile_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ myfile_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->


    <a href="{% url 'hide:myfile_create' %}" class="btn btn-primary">파일 등록하기</a>
    <a href="{% url 'hide:myfile_delete' request.user.id %}" class="btn btn-danger">모두 삭제</a>

</div>
{% endblock %}