server/demo/chat/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

server/demo/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'common'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name="common/login.html"), name='login'),
    path('login/', TemplateView.as_view(template_name='common/login.html'), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html'), name='logout'),
    path('signup/', TemplateView.as_view(template_name='common/signup.html'), name='signup'),

    path('email_verification/', TemplateView.as_view(template_name='common/email_verification.html'), name='email_verification'),
    path('password_reset/', TemplateView.as_view(template_name='common/password_reset.html'),
         name='password_reset'),
    path('password_reset_confirm/', TemplateView.as_view(template_name='common/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_change/', TemplateView.as_view(template_name='common/password_change.html'),
         name='password_change'),
]

server/demo/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from django.contrib import admin
from django.urls import include, path

from hide.views import base_views
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('hide/', include('hide.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path

    path('chat/', include('chat.urls')),


    # 인증 관련
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

handler404 = 'common.views.page_not_found'

server/demo/hide/urls.py
from django.urls import path

from .views import base_views, myfile_views
from .views import rest_pc_views, rest_mobile_views, rest_network_state_views

app_name = 'hide'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('myfile/', base_views.myfile_list, name='myfile_list'),

    # myfile_views.py
    path('myfile/create/', myfile_views.myfile_create, name='myfile_create'),
    path('myfile/modify/<int:current_author_id>/<int:myfile_id>/', myfile_views.myfile_modify, name='myfile_modify'),
    path('myfile/delete/<int:current_author_id>/', myfile_views.myfile_delete, name='myfile_delete'),

    # rest_pc_views.py
    path('myfile/rest/create/', rest_pc_views.rest_myfile_create, name='rest_myfile_create'),
    path('myfile/rest/delete/', rest_pc_views.rest_myfile_delete, name='rest_myfile_delete'),

    # rest_mobile_views.py
    path('myfile/rest/get_list/', rest_mobile_views.rest_get_myfile_list, name='rest_get_myfile_list'),

    # rest_network_state_views.py
    path('myfile/rest/get_network_state/', rest_network_state_views.rest_get_network_state, name='rest_get_network_state'),
]

server/demo/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

server/demo/templates/navbar.html
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">API endpoints <span class="caret"></span></a>

            <ul class="dropdown-menu" role="menu">
                <li>
                    {% if user.is_authenticated %}

                    <a href="/">{{ user.username }}</a>
                    {% else %}
                    <a href="{% url 'common:login' %}">please login</a>
                    {% endif %}
                </li>
                <li class="divider"></li>

                <!-- these pages don't require user token -->
                <li><a href="{% url 'common:signup' %}">Signup</a></li>
                <!--<li><a href="{% url 'common:email_verification' %}">E-mail verification</a></li>-->
                <li><a href="{% url 'common:login' %}">Login</a></li>
                <!--<li><a href="{% url 'common:password_reset' %}">Password Reset</a></li>-->
                <!--<li><a href="{% url 'common:password_reset_confirm' %}">Password Reset Confirm</a></li>-->

                <li class="divider"></li>

                <!-- these pages require user token -->
                <li><a href="{% url 'common:logout' %}">Logout</a></li>
                <li><a href="{% url 'common:password_change' %}">Password change</a></li>
            </ul>
          </li>
        </ul>

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="/">HIDE</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active">

                {% if user.is_authenticated %}
                <a href="{% url 'hide:myfile_list' %}">
                {{ user.username }}
                </a>

                {% else %}
                <a href="{% url 'common:login' %}">
                please login
                </a>
                {% endif %}

            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>